/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import characterScene from '../assets1/3d/soldier.glb';

function Soldier(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('./soldier.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <group name="Body_1">
          <skinnedMesh
            name="Cube004"
            geometry={nodes.Cube004.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cube004.skeleton}
          />
          <skinnedMesh
            name="Cube004_1"
            geometry={nodes.Cube004_1.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cube004_1.skeleton}
          />
          <skinnedMesh
            name="Cube004_2"
            geometry={nodes.Cube004_2.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cube004_2.skeleton}
          />
          <skinnedMesh
            name="Cube004_3"
            geometry={nodes.Cube004_3.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cube004_3.skeleton}
          />
          <skinnedMesh
            name="Cube004_4"
            geometry={nodes.Cube004_4.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Cube004_4.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('./soldier.glb');

export default Soldier;
